// NOTE: Generated by scripts/utils/updateImport
// Do not make edits here - they will be overwritten.
import AnimatedSprite from './AnimatedSprite/component.vue'
import Box from './Box/component.vue'
import CameraControls from './CameraControls/component.vue'
import CatmullRomCurve3 from './CatmullRomCurve3/component.vue'
import Circle from './Circle/component.vue'
import Cone from './Cone/component.vue'
import CubeCamera from './CubeCamera/component.vue'
import Cylinder from './Cylinder/component.vue'
import Dodecahedron from './Dodecahedron/component.vue'
import ExampleComponent from './ExampleComponent/component.vue'
import Grid from './Grid/component.vue'
import Html from './Html/component.vue'
import Icosahedron from './Icosahedron/component.vue'
import KeyboardControls from './KeyboardControls/component.vue'
import Line2 from './Line2/component.vue'
import MapControls from './MapControls/component.vue'
import Octahedron from './Octahedron/component.vue'
import OrbitControls from './OrbitControls/component.vue'
import Plane from './Plane/component.vue'
import PointerLockControls from './PointerLockControls/component.vue'
import Ring from './Ring/component.vue'
import RoundedBox from './RoundedBox/component.vue'
import ScrollControls from './ScrollControls/component.vue'
import Sky from './Sky/component.vue'
import Sphere from './Sphere/component.vue'
import StatsGl from './StatsGl/component.vue'
import Superformula from './Superformula/component.vue'
import Tetrahedron from './Tetrahedron/component.vue'
import Torus from './Torus/component.vue'
import TorusKnot from './TorusKnot/component.vue'
import TransformControls from './TransformControls/component.vue'
import Tube from './Tube/component.vue'

export {
  AnimatedSprite,
  Box,
  CameraControls,
  CatmullRomCurve3,
  Circle,
  Cone,
  CubeCamera,
  Cylinder,
  Dodecahedron,
  ExampleComponent,
  Grid,
  Html,
  Icosahedron,
  KeyboardControls,
  Line2,
  MapControls,
  Octahedron,
  OrbitControls,
  Plane,
  PointerLockControls,
  Ring,
  RoundedBox,
  ScrollControls,
  Sky,
  Sphere,
  StatsGl,
  Superformula,
  Tetrahedron,
  Torus,
  TorusKnot,
  TransformControls,
  Tube,
}
