// NOTE: Generated by scripts/utils.ts – 26/01/2025, 19:19:15
// Do not make edits here - they will be overwritten
import AnimatedSprite from './core/AnimatedSprite/component.vue'
import Box from './core/Box/component.vue'
import CameraControls from './core/CameraControls/component.vue'
import CatmullRomCurve3 from './core/CatmullRomCurve3/component.vue'
import Circle from './core/Circle/component.vue'
import Cone from './core/Cone/component.vue'
import CubeCamera from './core/CubeCamera/component.vue'
import Cylinder from './core/Cylinder/component.vue'
import Dodecahedron from './core/Dodecahedron/component.vue'
import ExampleComponent from './core/ExampleComponent/component.vue'
import GLTF from './core/GLTF/component.vue'
import Grid from './core/Grid/component.vue'
import Html from './core/Html/component.vue'
import Icosahedron from './core/Icosahedron/component.vue'
import KeyboardControls from './core/KeyboardControls/component.vue'
import Line2 from './core/Line2/component.vue'
import MapControls from './core/MapControls/component.vue'
import Octahedron from './core/Octahedron/component.vue'
import OrbitControls from './core/OrbitControls/component.vue'
import Plane from './core/Plane/component.vue'
import PointerLockControls from './core/PointerLockControls/component.vue'
import Ring from './core/Ring/component.vue'
import RoundedBox from './core/RoundedBox/component.vue'
import ScrollControls from './core/ScrollControls/component.vue'
import Sky from './core/Sky/component.vue'
import Sphere from './core/Sphere/component.vue'
import StatsGl from './core/StatsGl/component.vue'
import Superformula from './core/Superformula/component.vue'
import Tetrahedron from './core/Tetrahedron/component.vue'
import Torus from './core/Torus/component.vue'
import TorusKnot from './core/TorusKnot/component.vue'
import TransformControls from './core/TransformControls/component.vue'
import Tube from './core/Tube/component.vue'
import { useGLTF } from './core/GLTF/index'

export {
  AnimatedSprite,
  Box,
  CameraControls,
  CatmullRomCurve3,
  Circle,
  Cone,
  CubeCamera,
  Cylinder,
  Dodecahedron,
  ExampleComponent,
  GLTF,
  GLTF as GLTFModel,
  Grid,
  Html,
  Icosahedron,
  KeyboardControls,
  Line2,
  MapControls,
  Octahedron,
  OrbitControls,
  Plane,
  PointerLockControls,
  Ring,
  RoundedBox,
  ScrollControls,
  Sky,
  Sphere,
  StatsGl,
  Superformula,
  Tetrahedron,
  Torus,
  TorusKnot,
  TransformControls,
  Tube,
  useGLTF,
  useGLTF as useGLTFModel,
}
